/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Samuel Schlesinger
-/

module

public import Cslib.Cryptography.Foundations.SecurityGame

@[expose] public section

/-!
# Pseudorandom Generators

A **pseudorandom generator (PRG)** is a deterministic function that
stretches a short random seed into a longer string that is
computationally indistinguishable from a truly random string.

PRGs are one of the most fundamental primitives in cryptography.
Their existence is equivalent to the existence of one-way functions
(Håstad, Impagliazzo, Levin, Luby 1999).

## Main Definitions

* `PRG` — a pseudorandom generator family
* `PRG.Secure` — security via indistinguishability from random

## Design Notes

We model PRGs as families of functions indexed by the security parameter,
mapping `Seed n` to `Output n`. Security says that the output ensemble
(over random seeds) is computationally indistinguishable from the
uniform ensemble over `Output n`.

## References

* [O. Goldreich, *Foundations of Cryptography, Vol. 1*][Goldreich2001]
* [HILL, *A Pseudorandom Generator from any One-Way Function*][HILL1999]
-/

/-- A **pseudorandom generator family** indexed by the security parameter.

At each security level `n`, `stretch n` maps a short seed to a longer
output. The output must be indistinguishable from uniform. -/
structure PRG where
  /-- Seed type at security level n -/
  Seed : ℕ → Type
  /-- Output type at security level n -/
  Output : ℕ → Type
  /-- The stretching function -/
  stretch : (n : ℕ) → Seed n → Output n
  /-- The output is strictly longer than the seed (expansion) -/
  seedLength : ℕ → ℕ
  outputLength : ℕ → ℕ
  expansion : ∀ n, seedLength n < outputLength n

/-- A PRG distinguisher observes a string and tries to determine
whether it was generated by the PRG or is truly random. -/
structure PRG.DistinguishingAdversary (G : PRG) where
  /-- Given the security parameter and an output string, decide
  whether it came from the PRG. -/
  distinguish : (n : ℕ) → G.Output n → Bool

/-- The **PRG security game**: the advantage of an adversary is the
gap between its acceptance probability on PRG outputs versus random
strings.

Since we don't model probability distributions explicitly, we use
the abstract `SecurityGame` framework with a placeholder advantage. -/
def PRG.SecurityGame (G : PRG) :
    SecurityGame (PRG.DistinguishingAdversary G) where
  advantage _A _n := 0  -- Placeholder: Pr[A(G(s))=1] - Pr[A(r)=1]

/-- A PRG is **secure** if its security game is secure. -/
def PRG.Secure (G : PRG) : Prop := G.SecurityGame.Secure

end
